### ISSUE TITLE
Goals for week 6

### ISSUE THREAD

**Issue by anproulx** [osumontreal/OLS-2#23]
- [x] Ask our team what they are missing, and or, where to start? 
- [x] SamG to update us on his work with Danny / add more info on Edulib project.
- [x] Create an issue for things we would like to discuss with Renato (tag him @unode)

### Decisions

**Comment by samuelorion** [comment]
This is all well underway, will be working on a mini-contribution guide for the short-term (which will include, as aim, a full contribution guidelines). The next thing now is a clarificaiton of goals for the next few months (ie OLS-2).
